In [12]:
from google.cloud import bigquery

In [13]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [14]:
#Creating a client object
project_id = "sqlproject-302612"
client = bigquery.Client(project = project_id)

In [15]:
# fetching the data
dataset_ref = client.dataset("hacker_news", project = "bigquery-public-data")
dataset = client.get_dataset(dataset_ref)

In [16]:
# Listing the tables
tables = client.list_tables(dataset)
for table in tables:
  print(table.table_id)

comments
full
full_201510
stories

In [17]:
table_ref = dataset_ref.table("comments")
table = client.get_table(table_ref)

In [20]:
client.list_rows(table,max_results=10).to_dataframe()

         id  by author        time  ...    parent deleted  dead ranking
0   2701393  5l     5l  1309184881  ...   2701243    None  None       0
1   5811403  99     99  1370234048  ...   5804452    None  None       0
2     21623  AF     AF  1178992400  ...     21611    None  None       0
3  10159727  EA     EA  1441206574  ...  10159396    None  None       0
4   2988424  Iv     Iv  1315853580  ...   2988179    None  None       0
5   3867418  Iv     Iv  1334921984  ...   3867404    None  None       0
6   3925617  Iv     Iv  1336076765  ...   3924840    None  None       0
7   3107534  Iv     Iv  1318520044  ...   3107241    None  None       0
8   8409259  Iv     Iv  1412421647  ...   8409226    None  None       0
9   2855741  Jd     Jd  1312690646  ...   2855343    None  None       0

[10 rows x 10 columns]

In [21]:
## the query itself
query = '''
        SELECT parent, COUNT(1) AS Num_post
        FROM `bigquery-public-data.hacker_news.comments`
        GROUP BY parent
        HAVING COUNT(1) > 10
        '''

In [26]:
## Submitting the query
query_job = client.query(query)
n_posts = query_job.to_dataframe()
n_posts.head()

    parent  Num_post
0  3873271        50
1  5308611        63
2  5176140        63
3  9269660        51
4  9439286        69